language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install flake8
  - pip install pydocstyle
# command to run tests
script:
  - flake8 . --max-line-length=120
<<<<<<< HEAD
  - pydocstyle . --add-ignore=D202
=======
  - pep257 . --add-ignore=D202,D211
>>>>>>> Update .travis.yml
